### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by dsrukmana** [Nerdmind/Blog#12]
Nerdmind,

I have this error when try to access a single post, page, user, feed. I can access admin area and create /edit/delete a post just fine. Am I missing something?

**Comment by Nerdmind** [comment]
Hi. This sounds like an error or misconfiguration on your web server because the application never throws a 500 error itself. Do you have access to the `error.log` of your web server? I assume that you are using Apache and that the `mod_rewrite` module may be not loaded.

Please check if `mod_rewrite` is loaded.

**Comment by dsrukmana** [comment]
I'm just using shared hosting package, is this possible?

**Comment by Nerdmind** [comment]
I don't know, that depends on your hoster.

Is the blog installed within a sub directory (`/sub-directory/` instead of the root `/`)? If that is the case, you may need to define `RewriteBase /sub-directory/` within the `.htaccess` file after the line with the `RewriteEngine` directive.

If this is not the solution, please comment out each line from the `.htaccess` and then comment them in one by one and test on which line the 500 error occurs. I am pretty sure that the problem has to be somewhere there.

**Comment by dsrukmana** [comment]
Ok I get what you mean, but now I'm switched to cloud vps using Centos 7. Everything works fine (you were right the problem before is `mod_rewrite`) but now I have new issue, I can't login into admin area using the default uname:password it's redirect me back into login screen.

**Comment by Nerdmind** [comment]
Cool. So the `mod_rewrite` module wasn't enabled?

(please open a separate new issue for this other problem, I'll help you there)

**Comment by dsrukmana** [comment]
Yeah the problem was `mod_rewrite` wasn't enable.
