### ISSUE TITLE
How to make sidebar?

### ISSUE THREAD

**Issue by ghost** [Nerdmind/Blog#16]
Dear Developer!

I'd like to ask how to make a sidebar? It's like your blog.

Ich möchte fragen, wie man eine Sidebar erstellt? Es ist wie dein Blog. :)

Thank you!
Regards,
Lacesz

**Comment by Nerdmind** [comment]
Hi. Do you mean the recommended post list?

This is done manually within the template file `main.php` and with the undocumented function `POST()`, which will return an array [with all the keys listed here](https://github.com/Nerdmind/Blog/wiki/Templates/ee1872c79e265622055ad306bd9928a80ca1b3f7#post). If the item ID wasn't found, an empty array is returned instead. This also applies to the other two functions `PAGE()` and `USER()`.

~~~php
<ul id="recommended-list">
	<?php foreach([3, 9, 11, 139, 45, 136, 67, 131] as $postID): ?>
		<?php if($post = POST($postID)): ?>
			<li>
				<a href="<?=$post['URL']?>" title="<?=$Language->text('select_post')?> »<?=escapeHTML($post['ATTR']['NAME'])?>«">
					<?=escapeHTML($post['ATTR']['NAME'])?>
				</a>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
</ul>
~~~

I hope, I could help you with it?
– Thomas

**Comment by ghost** [comment]
Hello Thomas!
Thank you very much for youre replay.

I thought about that. But I want to what you see in the attachment:

![screenshot_2019-02-07_23-15-17](https://user-images.githubusercontent.com/842504/52446554-9fbd8b00-2b2e-11e9-9d54-d8afd8828850.png)

Regards,
Lacesz

**Comment by Nerdmind** [comment]
Hi. I don't exactly understand what you are asking for. The sidebar itself is just HTML and CSS, but [here is the complete markup](https://github.com/Nerdmind/Blog/files/2842992/sidebar-markup.php.txt) for the `<aside>`-Tag how I use it on my own template.

I hope, this is helpful. If this is a question like "How to make a sticky sidebar with HTML and CSS", then I can't help you, because this is a HTML/CSS thing.

– Thomas
