### ISSUE TITLE
How to disable auto list in post?

### ISSUE THREAD

**Issue by dillo1618** [Nerdmind/Blog#19]
Blog always convert '-' in start line to bulleted list when post display, but i don't want that because some lines are dialogues.

**Comment by Nerdmind** [comment]
This is intended behaviour because `-` at the beginning of a line starts an [unordered list](https://www.markdownguide.org/basic-syntax/#unordered-lists) in Markdown syntax. The solution is: You can [escape the character](https://www.markdownguide.org/basic-syntax/#escaping-characters) with a preceding backslash to prevent that the `-` is interpreted as Markdown.

**Comment by dillo1618** [comment]
> This is intended behaviour because `-` at the beginning of a line starts an [unordered list](https://www.markdownguide.org/basic-syntax/#unordered-lists) in Markdown syntax. The solution is: You can [escape the character](https://www.markdownguide.org/basic-syntax/#escaping-characters) with a preceding backslash to prevent that the `-` is interpreted as Markdown.

Thank you very much for support. I think you should add to script a tag to show more post on index, don't show full post on index page and function align text in editor.
